export const COLLEGES = [
    {
        id: 0,
        name: "Colorado State University",
        image: require("../components/images/CSU.jpeg"),
        location: "Fort Collins, Colorado",
        featured: true,
        type: "public",
        undergrads: "32,908",
        acceptance: "83.5%",
        averagegpa: "3.7",
        topmajors:
            "Human Development and Family Studies, Psychology, Kinesiology and Exercise Science",
    },
    {
        id: 1,
        name: "University of Northern Colorado",
        image: require("../components/images/unc.jpg"),
        location: "Greeley, Colorado",
        featured: false,
        type: "public",
        undergrads: "8,494",
        acceptance: "87.7%",
        averagegpa: "3.39",
        topmajors: "Registered Nursing, Psychology, Elementary Education",
    },
    {
        id: 2,
        name: "University of Colorado Boulder",
        image: require("../components/images/ucboulder.jpg"),
        location: "Boulder, Colorado",
        featured: false,
        type: "public",
        undergrads: "30,300",
        acceptance: "84.2%",
        averagegpa: "3.66",
        topmajors: "Business Administration, Psychology, Computer Science",
    },
    {
        id: 3,
        name: "Metropolitan State University",
        image: require("../components/images/metro.jpg"),
        location: "Denver, Colorado",
        featured: false,
        type: "public",
        undergrads: "17,988",
        acceptance: "83.3%",
        averagegpa: "2.6",
        topmajors:
            "Biology, Research and Experimental Psychology, Multi-Interdisciplinary Studies",
    },
    {
        id: 4,
        name: "University of Denver",
        image: require("../components/images/du.jpg"),
        location: "Denver, Colorado",
        featured: false,
        type: "private",
        undergrads: "12,000",
        acceptance: "60.7%",
        averagegpa: "3.72",
        topmajors:
            "Business, Management, and Marketing, Social Sciences, Psychology",
    },
    {
        id: 5,
        name: "Regis University",
        image: require("../components/images/regis.jpg"),
        location: "Denver, Colorado",
        featured: false,
        type: "private",
        undergrads: "3,197",
        acceptance: "78.2%",
        averagegpa: "3.57",
        topmajors: "Nursing, Business Administration, Computer Science",
    },
];
