export const COLLEGES = [
    {
        id: 0,
        name: "Colorado State University",
        image: require("../components/images/CSU.jpeg"),
        location: "Fort Collins, Colorado",
        featured: true,
        type: "public",
        description: "words",
    },
    {
        id: 1,
        name: "University of Northern Colorado",
        image: require("../components/images/unc.jpg"),
        location: "Greeley, Colorado",
        featured: false,
        type: "public",
        description: "words",
    },
    {
        id: 2,
        name: "University of Colorado Boulder",
        image: require("../components/images/ucboulder.jpg"),
        location: "Boulder, Colorado",
        featured: false,
        type: "public",
        description: "words",
    },
    {
        id: 3,
        name: "Metropolitan State University",
        image: require("../components/images/metro.jpg"),
        location: "Denver, Colorado",
        featured: false,
        type: "public",
        description: "words",
    },
    {
        id: 4,
        name: "University of Denver",
        image: require("../components/images/du.jpg"),
        location: "Denver, Colorado",
        featured: false,
        type: "private",
        description: "words",
    },
    {
        id: 5,
        name: "Regis University",
        image: require("../components/images/regis.jpg"),
        location: "Denver, Colorado",
        featured: false,
        type: "private",
        description: "words",
    },
];
