export const COLLEGES = [
    {
        id: 0,
        name: "Colorado State University",
        image: "/components/images/csu.png",
        location: "Fort Collins, Colorado",
        featured: true,
        type: "public",
        description: "words",
    },
    {
        id: 1,
        name: "University of Northern Colorado",
        image: "/components/images/csu.png",
        location: "Greeley, Colorado",
        featured: false,
        type: "public",
        description: "words",
    },
    {
        id: 2,
        name: "University of Colorado Boulder",
        image: "/components/images/csu.png",
        location: "Boulder, Colorado",
        featured: false,
        type: "public",
        description: "words",
    },
    {
        id: 3,
        name: "Metropolitan State University",
        image: "/components/images/csu.png",
        location: "Denver, Colorado",
        featured: false,
        type: "public",
        description: "words",
    },
    {
        id: 4,
        name: "University of Denver",
        image: "/components/images/csu.png",
        location: "Denver, Colorado",
        featured: false,
        type: "private",
        description: "words",
    },
    {
        id: 5,
        name: "Regis University",
        image: "/components/images/csu.png",
        location: "Denver, Colorado",
        featured: false,
        type: "private",
        description: "words",
    },
];
